on: push
name: xcode
jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=12.2,name=iPhone X', 'platform=tvOS Simulator,OS=12.2,name=Apple TV 4K']
    steps:
      - name: Checkout
        uses: actions/checkout@dev
      - name: Build and test
        run: |
          xcodebuild clean test -project TimeToGo.xcodeproj -scheme TimeToGo -destination "${destination}" CODE_SIGN_IDENTITY="9YZB6JT527" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
          bash <(curl -s https://codecov.io/bash)
        env: 
         destination: ${{ matrix.destination }}
